---
title: "DKOsimR Tutorial"
author:
date:
output: pdf_document
vignette: >
  %\VignetteIndexEntry{DKOsimR Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
# use the following command to generate pdf and html files in the same directory of .rmd
#rmarkdown::render("./vignettes/DKOsimR.Rmd", "html_document", output_dir="./vignettes")
#rmarkdown::render("./vignettes/DKOsimR.Rmd", "pdf_document", output_dir="./vignettes")

```


# Tutorial: How to generate synthetic CRISPR data using DKOsimR?

## 1. Introduction
This tutorial introduces DKOsimR package for generating synthetic CRISPR double knockout data. It mainly includes:

- Full list of all tunable parameters to initialize the simulation.
- Descriptions on how users may generate synthetic CRISPR data in two modes: 
  - default simulation, with 4 gene class: negative, wild-type, non-targeting control, positive
  - simulation applicable to approximate real lab data, with 3 gene class: negative (essential), unknown, non-targeting control


## 2. List of tunable parameters:
Let's go through the designed parameters in the simulation framework. Below list out all tunable parameters and how it is represented in DKOsimR.  

***Abbreviations: %, percentage; GI, genetic interaction; std. dev., standard deviation.***

- Initialized Library Parameters
  - `sample_name`: name of the simulation run
  - `coverage`: cell representation per guide
  - `n`: number of unique single gene
  - `n_guide_g`: number of guide per gene
  - `moi`: multiplicity of infection - % of cells that are transfected by any virus
  - `sd_freq0`: dispersion of initial counts distribution
  
- GI Parameters:
  - `p_gi`: % of genetic interaction presence
  - `sd_gi`: std. dev. of re-sampled phenotype with gi presence
  
- Guide Parameters:
  - `p_high`: % of high-efficacy guides
  - `mode`: CRISPR mode: 
    - use `CRISPRn-100%Eff` if need 100% efficient guides without randomization
    - use `CRISPRn` if need high-efficient guides draw from distribution
    
- Gene Class Parameters:  
  *1. % of theoretical phenotype to each gene class - make sure they add up to 1* 
  - `pt_neg`: % negative
  - `pt_pos`: % positive
  - `pt_wt`: % wild-type
  - `pt_ctrl`: % non-targeting control
  
  *2. Mean and std. dev. of theoretical phenotype*  
  - `mu_neg`: mean of negative genes
  - `sd_neg`: std. dev. of negative genes
  - `mu_pos`: mean of positive genes
  - `sd_pos`: std. dev. of positive genes
  - `sd_wt`: std. dev. of wild-type genes
  
- Bottleneck Parameters:  
  - `size.bottleneck`: bottleneck size - threshold indicating the ceiling of cell growth
  - `n.bottlenecks`: number of bottleneck encounters - how many times do we encountering bottlenecks?
  - `n.iterations`: number of maximum doubling cycles, by default, we assume a maximum of 30 doublings if we didn't encounter bottleneck
  
- Randomization Parameter:
  - `rseed`: values used for random number generator - use same number to control same sets of genes having GI

## 3. Running Simulation



## 4. Laboratory Data Pattern Approximation

